P4-Games/ChatterPay-Backend

- README.md
- [docs] 📝 update project documentation
> merge feature/docs into main

- src/controllers/nftController.ts
- src/models/nft.ts
- [feat] 🚚 rename nft to nfts and add wallet field
> merge feature/nft-wallet into staging

- src/controllers/demoERC20Controller.ts
- src/controllers/nftController.ts
- src/routes/nftRoutes.ts
- [feat] 🚚 rename nft to nfts and add wallet field
> merge staging into main

- src/controllers/replyController.ts
> merge feature/bot-base-url into develop

- .github/workflows/codeql-check.yml
> merge feature/codeql into develop

- src/controllers/nftController.ts
- src/controllers/replyController.ts
- src/models/nft.ts
- src/utils/uploadServices.ts
- [fix] 🐛 fix lat,lng schema (#17)
- [fix] 🐛 fix errors geolocation, nft mint (#17, #16)
> merge fix/mint-nft into develop

- src/models/nft.ts
> merge fix/copy-original-type into develop

- src/constants/contracts.ts
- src/controllers/nftController.ts
- src/controllers/replyController.ts
- [fix] 🐛 remove sequencial id
- [feat] ✨ add default nft image
- [feat] ✨ add new method to notify user
- [refactor] ♻️ refactor nft mint
> merge fix/mint into develop

- src/controllers/nftController.ts
- src/controllers/replyController.ts
- src/models/nft.ts
- [refactor] :recycle: refactor nft messages
> merge fix/mint-refactor into develop

- src/controllers/nftController.ts
- [refactor] ♻️ refactor nft messages
> merge refactor/mint-3 into develop

- src/controllers/nftController.ts
- [fix] :bug: update reply return
> merge fix/reply into develop

- src/config/database.ts
- src/controllers/replyController.ts
- **[chore] add some logs**
- **[remove] functions of operator/assistant switch and add logs**
> Remove Operator Reply. Close #57

- .env.example
- src/models/blockchain.ts
- **[feat] Modify Schema for externalize contract addresses**
- **[update] .env.example**
> Move Blockchain-related environment variables to the DB. Closes#64

- src/api/nftRoutes.ts
- src/config/database.ts
- src/controllers/nftController.ts
- src/controllers/replyController.ts
- src/controllers/swapController.ts
- src/models/blockchain.ts
- src/models/nft.ts
- src/services/predictWalletService.ts
- src/services/walletService.ts
- src/utils/dynamicGas.ts
[feat] :label: convert nft id to string (#68)
> merge feature/nft-id-string into develop

- src/controllers/nftController.ts
- src/controllers/replyController.ts
- src/services/predictWalletService.ts
- src/services/walletService.ts
- [chore] 🔥 remove unused code
- [fix] 🚑 fix errro with types (contracts)
> merge fix/types into develop

- src/controllers/replyController.ts
- [fix] :ambulance: fix errro with types (contracts)
> merge fix/types-2 into develop

- src/controllers/replyController.ts
[fix] :bug: fix typo in contract variable used with open-sea url
> merge fix/typo into develop

- src/controllers/replyController.ts
[fix] :bug: fix typo in contract variable used with open-sea url
> merge hotfix/open-sea-url into main

- src/constants/contracts.ts
- src/controllers/nftController.ts
- src/controllers/replyController.ts
- src/controllers/transactionController.ts
- src/models/nft.ts
- src/services/networkService.ts
- src/services/predictWalletService.ts
- src/services/transactionsService.ts
- src/services/walletService.ts
- src/utils/uploadServices.ts
> merge feature/2024103 into develop

- src/controllers/nftController.ts
- src/models/nft.ts
> merge feature/20241003-2

- src/controllers/nftController.ts
- src/models/nft.ts
> merge feature/20241003-3 into develop

- src/config/database.ts
- src/config/server.ts
- src/constants/contracts.ts
- src/controllers/balanceController.ts
- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/tokenController.ts
- src/services/predictWalletService.ts
- src/services/walletService.ts
- src/utils/uploadServices.ts
- src/utils/web3_config.ts
> Move use of environment variables to a constants file

- src/config/database.ts
- src/config/server.ts
- src/constants/contracts.ts
- src/controllers/balanceController.ts
- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/tokenController.ts
- src/services/predictWalletService.ts
- src/services/walletService.ts
- src/utils/uploadServices.ts
- src/utils/web3_config.ts
Reverts P4-Games/ChatterPay-Backend#100
> Revert "Move use of environment variables to a constants file"

- src/config/database.ts
- src/config/swagger.ts
- src/constants/environment.ts
- src/controllers/nftController.ts
- src/utils/uploadServices.ts
- [fix] 🐛 fix login in read icp and ipfs env vars
- [feat] 🚨 linter
> merge 20241004-1 into develop

- src/api/nftRoutes.ts
- src/config/swagger.ts
- src/constants/environment.ts
- src/controllers/nftController.ts
- src/services/bucketService.ts
> merge feature/20241005-1 into develop

- src/api/nftRoutes.ts
- src/config/swagger.ts
- src/constants/environment.ts
- src/controllers/nftController.ts
- src/services/bucketService.ts
- [chore] 💄 prettier & linter
- [feat] ♻️ adapt logic to new methods to mint original/copy nft (#107)
> merge feature/20241005-2 into develop

- cloudbuild.yaml
- [build] 👷 add section to print secret-variables in cloudbuild
- [build] 👷 update cloudbuild.yaml file
> merge feat/improve-dockerfile into develop

- src/controllers/nftController.ts
> Fix: NFT original minting

- src/config/publicRoutes.ts
- src/middleware/authMiddleware.ts
- src/types/requests.ts
Closes: [#148](https://github.com/P4-Games/ChatterPay-Backend/issues/148)
> Added config file for public routes

- src/controllers/replyController.ts
- src/controllers/transactionController.ts
- src/middleware/authMiddleware.ts
- src/services/transferService.ts
- src/services/userOperationService.ts
- src/utils/paymaster.ts
Cierra: #149 
Prueba:
https://sepolia.arbiscan.io/tx/0x268d137fa4151d40ffa8eb5205a9653f770b1f455792db6b8bf50b08bde0a26c
> Improved paymaster signature in make_transaction

- src/config/publicRoutes.ts
- src/controllers/balanceController.ts
- src/controllers/swapController.ts
- src/services/externalDepositsService.ts
> Release review

- src/controllers/replyController.ts
- src/services/externalDepositsService.ts
- This PR introduces non breaking changes such as rounding decimals, and link change.
- POST /mint
- POST /mint_existing
- POST /swap
> Improved rounding in swap, added NFT share link to mint notification 

- src/controllers/nftController.ts
> merge feature/160 into develop

- src/constants/environment.ts
- src/services/userService.ts
- [feat] 🔧 replace arbitrum-sepolia by ethereum-sepolia to use with push
- [fix] ✏️ fix typo
> merge feature/push-delegate into develop

- scripts/subscribe_wallets_to_push_channel.ts
-  [feat] :hammer: update dev script to allow subscribe existing users to push channel
> merge feature/push-subscriptions into develop

- src/controllers/nftController.ts
- [fix] 🐛 replace _id by id when fetching metadata from bdd
- [Revert] ⏪ Revert NFT id replacement and apply correct validation
> merge fix/20241225 into develop

- src/controllers/transactionController.ts
- src/services/swapService.ts
- src/services/transferService.ts
- src/services/walletService.ts
- [refactor] ♻️ refactor duplicated function check-wallet-balance 
- [refactor] 🌐 translate some message from spanish to english
> merge feature/20241225-2 into develop

- src/services/notificationService.ts
- [fix] 🩹 fix notification type in templates
- [refactor] ♻️ refactor return types and return data
- [chore] 🔇 remove logs
> merge fix/notifications-types into develop

- src/controllers/nftController.ts
- [fix] 🐛 fix request parameters validation in mint-nft-original
> merge fix/nft-original-validation

- .doc/content.md
- .doc/deployment/deployment-guidelines.md
- .doc/development/development-guidelines.md
- .doc/technical-overview/componentes-Interactions.md
- [docs] 📝 add info about backend interactions (internal / external)
- [docs] 📝 add general development documentation and index
- [docs] 📝 update style in components-interaction documentation
> merge feature/docs-backend-interactions into develop

- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/controllers/walletController.ts
- src/services/blockchainService.ts
- src/services/swapService.ts
- src/services/transferService.ts
- src/services/userOpExecutorService.ts
- src/services/userOperationService.ts
- src/services/walletService.ts
- [refactor] ♻️ update text in some console logs
- [refactor] ♻️ join wallets balances functions in one service
- [refactor] ♻️ update references to verifiyWalletBalance
- [docs] 📝 add documentation in header of verifiyWalletBalance
- [refactor] 🚚 rename checkWalletBalance to verifyWalletBalance
- [refactor] 🚚 move tokenAddresses type to blockchain Service
- [refactor] ♻️ replace fixed decimals by contract decimals in verifyWalletBalance 
- [refactor] ♻️ Unify getTokenAddress and getBalances functions in SwapService
- [refactor] ♻️ refactor request validations in transaction Controller
- [refactor] ♻️ refactor request validations in swap Controller
> merge feature/verify-balance into develop

- src/controllers/nftController.ts
- src/controllers/walletController.ts
- src/services/walletService.ts
- [fix] ✏️ fix typo in opensea url when get certificates
- [chore] ⚰️ remove dead code
- [chore] 🔊 update balance messages in console
> merge fix/make-transaction into develop

- .gitignore
- scripts/subscribe_wallets_to_push_channel.ts
- scripts/update_users_wallet_eoa.ts
- src/models/user.ts
- src/services/notificationService.ts
- src/services/userService.ts
- src/utils/dynamicGas.ts
- [feat] 🔨 add dev script to update walletEOA in users
- [refactor] 🔨 refactor dev scripts
- [chore] 🧑‍💻 ignore env files
- [fix] 🐛 fix error with estimated gas limit 
- [refactor] ⚰️ remove dead code in dynamicGas file 
- [feat] 📝 make the walletEOA field mandatory in type 
- [feat] 👔 add function to get user in userService
- [refactor] ♻️ ensure push notif are sent to the EOA account 
- [refactor] ♻️ prettier stuff in dev scripts
> merge feature/20241229-1 into release/v0.0.9

- .gitignore
- scripts/subscribe_wallets_to_push_channel.ts
- scripts/update_users_wallet_eoa.ts
- src/models/user.ts
- src/services/notificationService.ts
- src/services/userService.ts
- src/utils/dynamicGas.ts
- [feat] 🔨 add dev script to update walletEOA in users
- [refactor] 🔨 refactor dev scripts
- [chore] 🧑‍💻 ignore env files
- [fix] 🐛 fix error with estimated gas limit
- [refactor] ⚰️ remove dead code in dynamicGas file
- [feat] 📝 make the walletEOA field mandatory in type
- [feat] 👔 add function to get user in userService
- [refactor] ♻️ ensure push notif are sent to the EOA account
- [refactor] ♻️ prettier stuff in dev scripts
> merge release/v0.0.9 into develop

- src/constants/environment.ts
- src/controllers/nftController.ts
- src/models/blockchain.ts
- src/services/externalDepositsService.ts
- src/services/notificationService.ts
- src/services/predictWalletService.ts
- [feat] 📝 add marketplace url to blockchain type
- [feat] ✨ use marketplace url from bdd 
- [refactor] ♻️ move gasLimit calculation outside tx function 
- [refactor] ♻️ add chatterpay domain and nfts url in constants
- [refactor] ♻️ use chatterpay domain and nfts url in notifications 
- [refactor] 🌐 translate text to english in externalDepositService
- [style] 🎨 prettier
> merge fix/20241229-2 into develop

- src/controllers/balanceController.ts
- src/controllers/swapController.ts
- src/services/walletService.ts
- src/types/token.ts
- [perf] ⚡ implement cache in getTokenPrices 
- [fix] 🐛 fix swap 2nd transaction 0 and refactor 
- [refactor] ♻️ move getTokenPrices from controller to service
> merge feature/230_231 into develop

- src/constants/environment.ts
- src/models/user.ts
- src/services/notificationService.ts
- src/services/userService.ts
- [feat] ✨ add settings default language as constant 
- [feat] ✨ use user settings language to send notifications
- [styles] 💡 add comments to functions headers
> merge feature/push-use-user-lng into develop

- src/constants/environment.ts
- src/models/templates.ts
- src/services/notificationService.ts
- src/services/templateService.ts
- [feat] 🗃️ add templates model 
- [feat] ✨ add settings language to env definition 
- [feat] ✨ add templates service 
- [feat] 👔 update notifications to use templates
> merge feature/notifications-templates into develop

- scripts/initLastProcessedBlock.ts
- src/models/blockchain.ts
- [chore] 🔊 update log in initializeLastProcessedBlock
- [feat] 🗃️ replace beacon by simpleswap field in blockchains model
> merge feature/20250103 into develop

- src/constants/environment.ts
- src/middleware/bodyParser.ts
- src/models/templates.ts
- src/services/notificationService.ts
- src/utils/logger.ts
- [feat] 🥅 prevent interruption due to error in Logger class
- [refactor] 🧑‍💻 improve logging stuffs in bodyParser 
- [styles] 🎨 prettier
> merge fix/parsebody-logging-error into develop

- src/constants/blockchain.ts
- src/controllers/balanceController.ts
- src/controllers/swapController.ts
- src/services/externalDepositsService.ts
- src/services/swapService.ts
- [feat] 🔥 remove simple swap contract address from constants
- [feat] ✨ use simpleSwapAddress from bdd in checkExternalDeposits 
- [feat] ✨ use simpleSwapAddress from bdd in swapController
- [feat] ✨ use simpleSwapAddress from bdd in fetchExternalDeposits 
- [feat] ✨ use simpleSwapAddress from bdd in swapService
> merge feature/simple-swap-to-bdd into develop

- src/controllers/tokenController.ts
- src/models/blockchain.ts
- [feat] 🗃️ add environment field in blockchain schema
- [feat] 🔐 disable /issue endpoint in production
> merge feature/disable-issue-tokens-in-prod into develop

- src/controllers/swapController.ts
- src/controllers/walletController.ts
- src/services/transferService.ts
- [fix] 🩹 replace eoa by proxy in wallet creation response 
- [fix] 🩹 fix fastify reply return twite 
- [refactor] 🔊 update log errors in swap controller 
- [refactor] 🧑‍💻 improve userOperation log error
> merge fix/20250105 into develop

- src/constants/environment.ts
- src/services/paymasterService.ts
- src/services/swapService.ts
- src/services/transferService.ts
- [refactor] 🚚 move balance-related variables to constants 
- [feat] ♻️ refactor paymaster service balance checks
- [feat] ♻️ refactor swap service balance checks 
- [feat] ♻️ refactor transaction service balance checks
> merge feature/check-backend-signer-balance into develop

- src/constants/environment.ts
- src/controllers/swapController.ts
- src/models/templates.ts
- src/services/blockchainService.ts
- src/services/bundlerService.ts
- src/services/contractSetupService.ts
- src/services/gasService.ts
- src/services/notificationService.ts
- src/services/paymasterService.ts
- src/services/swapService.ts
- src/services/transferService.ts
- src/services/userOperationService.ts
- src/services/walletService.ts
- src/types/common.ts
- src/types/logger.ts
- src/types/userOperation.ts
- src/utils/logger.ts
- src/utils/userOperation.ts
- [feat] ✨ add new notification templates to types 
- [feat] ✨ create check-blockchain-conditions functions 
- [feat] ✨ add send User Insufficient Balance Notification 
- [feat] ✨ add No Valid Blockchain Conditions Notification 
- [feat] ✨ add internal error Notification 
- [refactor] 🚚 update types name
- [refactor] 🚚 move types to types folder
- [refactor] 🚚 move signers balance checker to blockchain-service
- [refactor] ♻️ refactor swap-controller to include new notifications 
- [refactor] ♻️ refactor swap-service to include new notifications 
- [style] 🏷️ add return type to setupContracts function 
- [chore] 💡 update some function comments
> merge feature/swap-no-balance-notifications into develop

- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/services/bundlerService.ts
- src/services/notificationService.ts
- src/services/swapService.ts
- src/services/transferService.ts
- src/types/common.ts
- src/utils/logger.ts
- [fix] 🐛 add missing await in swap logic 
- [feat] 🏷️ add execute-transaction result type
- [feat] ✨ es: ensure blk conditions before withdraw-all
- [refactor] 🔥 remove unused param in notification service
- [refactor] ♻️ refactor trx controller to ensure blk conditions 
- [refactor] ♻️ refactor transfer service 
- [refactor] ♻️ join save-transaction in one function
- [styles] 🎨 linter stuffs
- [styles] 🎨 improve swap service code
> merge feature/blk-conditions into develop

- src/controllers/ImageController.ts
- src/controllers/balanceController.ts
- src/controllers/nftController.ts
- src/controllers/transactionController.ts
- src/controllers/walletController.ts
- src/helpers/formatHelper.ts
- src/models/user.ts
- src/services/externalDepositsService.ts
- src/services/notificationService.ts
- src/services/userService.ts
- src/services/walletService.ts
- [fix] 🩹 remove extra parameter in call to sendTransferNotification
- [feat] ✨ add creation date in user service
- [feat] ✨ add creation date in user model 
- [feat] ✨ add formathelper
- [feat] ✨ use common function to get/create user in nftController
- [feat] ✨ format phone with helper in walletServce
- [feat] ✨ format phone with helper in userServce
- [feat] ✨ format phone with helper in notificationServce
- [refactor] 💡 update comments in methods 
- [refactor] 💡 update comments in code
- [refactor] ♻️ use common getUser function in walletController
- [refactor] ♻️ use common getUser function in transactionController
- [refactor] ♻️ use common getUser function in balanceController
- [refactor] ♻️ use common getUser function in imageController
> merge feature/prevent-duplicated-users into develop

- src/controllers/nftController.ts
[fix] :bug: replace incorrect use of createWallet with getOrCreateUser in mintNFT
> merge fix/duplicated-users into develop

- scripts/fund_users_wallets.ts
- scripts/subscribe_wallets_to_push_channel.ts
- scripts/update_users_wallet_data.ts
- scripts/update_users_wallet_eoa.ts
- src/controllers/balanceController.ts
- src/controllers/nftController.ts
- src/controllers/transactionController.ts
- src/controllers/walletController.ts
- src/models/user.ts
- src/services/externalDepositsService.ts
- src/services/notificationService.ts
- src/services/transferService.ts
- src/services/uploadService.ts
- src/services/userService.ts
- src/services/walletService.ts
- [feat] ✨ add logic to handle wallets collection 
- [feat] ✨ adapt userModel to multi-wallet schema 
- [feat] ✨ adapt walletService to new wallets collection 
- [feat] ✨ adapt notificationService to new wallets collection 
- [feat] ✨ adapt externalDepositService to new wallets collection 
- [feat] ✨ adapt walletController to new wallets collection 
- [feat] ✨ adapt balanceController to new wallets collection 
- [feat] ✨ adapt transactionController to new wallets collection 
- [feat] ✨ adapt nftController to new wallets collection 
- [feat] ✨ adapt uploadService to new wallets collection 
- [feat] ✨ adapt walletService to new wallets collection 
- [feat] 🔨 add script to refactor wallets data in bdd 
- [feat] 🔨 adapt dev script to new wallets collection
> merge feature/user-wallets-collection into develop

- src/controllers/nftController.ts
- src/controllers/transactionController.ts
- src/controllers/walletController.ts
- src/services/userService.ts
- [fix] :adhesive_bandage: add missing chatterpay-implementation value in wallets
> merge fix/add-missing-chatterpay-implementation into develop

- scripts/update_users_notif_language.ts
- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/controllers/walletController.ts
- src/helpers/SecurityHelper.ts
- src/helpers/validationHelper.ts
- src/services/predictWalletService.ts
- src/services/userService.ts
- [feat] 🦺 update phone_number request validation 
- [fix] 🩹 fix wallet creation response
- [feat] 🔥 remove unnecessary concurrency operation notification in transfer 
- [feat] 🔥 remove unnecessary concurrency operation notification in swap
- [feat] 🔥 remove unnecessary concurrency operation notification in nft mint
- [feat] ✨ use clean phone-number in generatePrivsteKey
- [feat] ✨ use clean phone-number in predcitWalletService
- [feat] ✨ use clean phone-number in userService
> merge feature/request-validations into develop

- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- [feat] :sparkles: update error message when send templates
> merge feature/msg-templates into develop

- .eslintrc.json
- .github/workflows/linter-check.yml
- scripts/subscribe_wallets_to_push_channel.ts
- src/middleware/bodyParser.ts
- src/plugins/networkConfig.ts
- src/services/blockchainService.ts
- src/services/bundlerService.ts
- src/services/externalDepositsService.ts
- src/services/notificationService.ts
- src/services/userOpExecutorService.ts
- src/services/userService.ts
- src/services/walletService.ts
- [fix] 🚨 fix linter:no-use-before-define in services and scripts
- [fix] 🚨 fix linter:no-param-reassign in code
- [chore] 🏗️ update linter config to be more strict 
- [build] 💚 add github workflow to check linter 
- [build] 💚 add github workflow to check linter
- [build] 💚 add legacy-peer-deps in github workflow
- [build] 💚 update linter workflow to run in all pull-requests
> merge fix/linter-improves into develop

- cloudbuild.yaml
- [build] :bug: fix Cloud Build manteca_api_key defined more than once
> merge fix/cloud-build-2 into develop

- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/services/transferService.ts
- src/services/userService.ts
- [feat] :necktie: Update user operations check to validate any operation in progress
> merge feature/enhance-user-operations-checks into develop

- .doc/technical-overview/components-Interactions.md
- .github/workflows/PULL_REQUEST_TEMPLATE.md
- src/controllers/supportController.ts
- [chore] :memo: add PR template
> merge feature/github-template-pr into develop

- src/config/constants.ts
- src/middleware/traceMiddleware.ts
- src/services/bundlerService.ts
- src/services/gasService.ts
- [fix] 🐛 add missing trace-header in endpoints (#321)
- [refactor] ♻️ move queue time-intervals to constants
- [fix] 🚨 fix format
> merge feature/20240114-2 into develop

- src/config/middlewares/ipsBlackListMiddleware.ts
- [fix] :lock: improve IP blacklist middleware to handle proxies
> merge fix/blacklist-x-forward into develop

- src/controllers/transactionController.ts
- src/services/notificationService.ts
- [fix] 🩹 use cloud-trace-enabled from constants 
- [feat] 🚸 replace wallet by phone to send in transfer msg
- [refactor] ⚰️ remove unused parameter in notification
> merge fix/20250115-2 into develop

- src/config/constants.ts
- src/config/plugins/networkConfigPlugin.ts
- [fix] 🐛 fix error in refresh tokens and networks
- [refactor] ♻️ add env variable to use in network plugin
- [refactor] ♻️ replace harcoded intervals in networkconfig plugin
- [refactor] ♻️ refactor and improve networkconfig plugin
> merge fix/setup-network-config-plugin into develop

- .doc/technical-overview/components-Interactions.md
- src/config/constants.ts
- src/controllers/rampController.ts
- src/controllers/transactionController.ts
- src/services/balanceService.ts
- src/services/criptoya/criptoYaService.ts
- src/services/externalDepositsService.ts
- src/services/icp/icpService.ts
- src/services/ipfs/ipfsService.ts
- [refactor] 🚚 move pinata ipfs url to constants
- [refactor] 🚚 move infura url to constants
- [refactor] 🚚 move binance api url to constants
- [refactor] 🚚 move criptoYa url to constants
- [refactor] 🚚 move manteca mock upload docs url to constants
- [refactor] 🚚 move manteca mock icp agent url to constants
- [refactor] 🚚 move manteca mock the-graph url to constants
> merge feature/refactor-urls into develop

- src/services/web3/gasService.ts
- [fix] :rotating_light: fix linter warning
> merge fix/20250119 into develop

- package.json
- [feat] :hammer: add output folder in generate-types script
> [feat] :hammer: add output folder in generate-types script

- src/config/constants.ts
- src/config/plugins/swaggerPlugin.ts
- [feat] ✨ add dev phone number
- [refactor] ♻️ adapt swagger dev/main urls based on environment
> merge feature/url-phone-dev into develop

- scripts/subscribe_wallets_to_push_channel.ts
- scripts/update_users_wallet_eoa.ts
- src/helpers/SecurityHelper.ts
- src/services/blockchainService.ts
- src/services/predictWalletService.ts
- [feat] ✨ include chain_id in wallet generation
- [feat] ✨ include new chain_id parameter in phone to address fn 
- [feat] ✨ include new chain_id parameter in generatePrivateKey calls
> merge feature/wallet-generation into develop

- src/helpers/SecurityHelper.ts
- [feat] :sparkles: include environment in wallet generation
> merge feature/wallet-generation-2 into develop

- .doc/technical-overview/components-Interactions.md
- [docs] 📝 add binance to components-interactions
- [docs] 📝 add api3 to components-interactions
> merge feature/docs-1 into develop

- cloudbuild.yaml
- [build] 🐛 add missing build-arg in cloudbuild.yaml
> merge fix/abis-version-2 into develop

- src/config/middlewares/ipsBlackListMiddleware.ts
- src/controllers/swapController.ts
- src/services/mongo/mongoTransactionService.ts
- src/services/transferService.ts
- src/services/web3/paymasterService.ts
- src/types/commonType.ts
- [fix] 🐛 save withdraw-all transactions in bdd 
- [feat] 🏷️ add transaction-data type
- [feat] 🏷️ add transaction-data type as parameter in save-trx 
- [feat] 🏷️ add transaction-data type in save swap-trxs 
- [chore] 🔊 update messages in paymaster log entries
- [fix] 🔊 remove extra character in log entry
- [style] 🚨 fix linter stuff in paymaster functions
- [style] 🚨 fix linter format in paymaster-service
> merge fix/withdraw into develop

- .doc/technical-overview/components-Interactions.md
- src/controllers/transactionController.ts
- src/helpers/formatHelper.ts
- src/services/externalDepositsService.ts
- src/services/notificationService.ts
- [fix] 🐛 fix incorrect phone number in transfer msg
- [feat] ✨ add function to concat phone and user name
- [feat] ✨ include user name in transfer msg 
- [docs] 📝 update notifications documentation
> merge fix/transfer-notification into develop

- src/helpers/formatHelper.ts
- src/services/notificationService.ts
- [feat] ✨ allow to mask phone in helper function 
- [feat] ✨ mask phone number in transfer push notification
> merge feature/mask-phone-in-push to develop

- src/config/constants.ts
- [feat] :mute: exclude /favicon.ico from cors middleware
> merge feature/20250201-1 into develop

- src/services/web3/contractSetupService.ts
- src/services/web3/userOperationService.ts
- [fix] :bug: use correct chatterPay contract address in setupContract
> merge fix/setupcontracts-wrong-adress into develop

- src/services/web3/userOpExecutorService.ts
- [perf] :zap: reduce timeout from 20 to 5 min in waitForUserOperationReceipt
> merge feature/receipt-time-info into develop

- src/config/constants.ts
- [feat] :sparkles: adjust paymaster min values required
> merge feature/adjust-paymaster-min-values into develop

- .github/workflows/ci-check.yml
- src/config/constants.ts
- src/controllers/transactionController.ts
- src/services/swapService.ts
- src/services/transferService.ts
- src/services/web3/paymasterService.ts
- src/services/web3/userOperationService.ts
- test/setupTests.ts
- vitest.config.ts
- [feat] added retry system for txs w/ underpriced gas
- [format] ran prettier auto formatter
- [test] added setup to fix mongo setup errors
- [format] ran prettier auto formatter
- [feat] ✨ set gas costs by user operation
- [chore] 🔊 update log entries about paymaster cost info
> merge fix/swap-underpriced-tx into develop

- src/config/constants.ts
- src/models/blockchainModel.ts
- test/models/blockchainModel.test.ts
- test/models/lastProcessedBlockModel.test.ts
[build] 🔧 allow use 'testing' or 'development' as dev env
[refactor] ⚰️ remove old scanApiKey field
> merge fix/20250803 into develop

- src/services/predictWalletService.ts
- [refactor] :recycle: removed harcoded blockchain name in predictedWalletService
> merge fix/harcoded-blockchain-name into develop

- package.json
- src/controllers/nftController.ts
- src/models/nftModel.ts
- test/models/nftModel.test.ts
- [feat] ✨ add minted_contract_address in nft model
- [feat] ✨ add minted_contract_address in nft controller
- [feat] ✨ add minted_contract_address in nft tests
- [chore] 📝 translate package.json description
- [fix] 🐛 Fix translation of latitude & longitude fields in nft model
- [fix] 🐛 Fix translation of latitude & longitude fields in nft controller
- [fix] 🐛 Fix translation of latitude & longitude fields in nft tests
> merge feature/nft-save-minted-contract-adr into develop

- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/services/notificationService.ts
[feat] ✨ improve user experience with inverted error messages (#409)
[feat] ✨ send delay param from main services to notif service (#409)
[refactor] ♻️ remove dead code in mint nft
> merge feature/20259313 into develop

- src/config/middlewares/originMiddleware.ts
- src/controllers/nftController.ts
- src/helpers/paymasterHelper.ts
- src/services/predictWalletService.ts
- src/services/web3/gasService.ts
- Refactored of the getDynamicGas function, moved to the Gas service, updated default values in case automatic calculation fails. Impact on mintOrigina, mintCopy, and createWallet.
- [refactor] ♻️ refactor and move getDynamicGas 
- [refactor] ♻️ use cors_origins from constants in originMiddleware
> merge fix/generic-estimated-gas into develop

- src/controllers/balanceController.ts
- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- Previously, when a user without an existing wallet attempted to check their balance or perform a transaction, the system validated the user's existence but did not send a notification to the bot. As a result, users did not receive a friendly message. This behavior has now been corrected, and an appropriate notification is sent to ensure clear communication with the user.
- [feat] ✨ add specific notif for missing user wallet on transfer 
- [feat] ✨ add specific notif for missing user wallet on swap 
- [feat] ✨ add specific notif for missing user wallet on nft mint 
- [feat] ✨ add specific notif for missing user wallet on get balance
> merge feature/wallet-not-found into develop

- src/controllers/nftController.ts
- src/models/nftModel.ts
- test/models/nftModel.test.ts
- [feat] ✨ add chain_id in nft model
- [feat] ✨ add chain_id in nft controller
- [feat] ✨ add chain_id in nft model tests
> merge feature/chain-id-in-nft into develop

- src/services/web3/userOperationService.ts
- [refactor] ♻️ refactor waitForUserOperationReceipt to use POST call
> merge feature/20250413-3 into develop

- scripts/swap_debug/common.ts
- scripts/swap_debug/create_proxy.ts
- scripts/swap_debug/eoa_direct_swap.ts
- scripts/swap_debug/pre_swap_validations.ts
- scripts/swap_debug/proxy_direct_swap.ts
- To improve maintainability across the Uniswap development scripts, the `resolveRpcUrl` helper function was added to `common.ts` for consistent RPC handling. Minor cleanups were performed, including commenting out the owner validation logic and the unused `recipient` variable to streamline the swap execution scripts. Additionally, the logic for waiting on transaction confirmations during token approvals was updated to ensure better reliability.
> merge feature/20250429 into develop

- src/config/constants.ts
- [feat] :sparkles: update default language settings to en
> merge feature/20250506-2 into develop

- example_env
- scripts/breaking_point.ts
- [chore] :hammer: add development script to check transactions
> merge feature/20250509 into develop

- src/services/userService.ts
This PR adds a validation to the `createUserWithWallet` function to skip subscribing to the push channel when `PUSH_ENABLED` is false, ensuring that users without push notifications enabled are not subscribed. It also includes a log message indicating when the subscription process is skipped due to notifications being disabled.
- #472
> merge feature/20250512 into develop

- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/services/blockchainService.ts
- [refactor] :recycle: refactor operations-lmits functions (#430)
> merge feature/20250512-2 into develop

- src/controllers/nftController.ts
- src/services/blockchainService.ts
- src/services/predictWalletService.ts
- src/services/web3/paymasterService.ts
- This PR introduces the addition of the gasPrice parameter to transactions that fund both the Paymaster and the User. The gas price is now dynamically calculated and included in the transaction options to ensure accurate fee estimation and transaction execution.
- #484
> merge feature/484-gas-price-parameter into develop

- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/models/transactionModel.ts
- src/services/externalDepositsService.ts
- src/services/mongo/mongoTransactionService.ts
- src/services/transferService.ts
- src/types/commonType.ts
- test/models/transactionModel.test.ts
- This PR adds the "fee" field across multiple components of the transaction flow, including the transaction model, transaction types, and transaction tests for validation. It incorporates fee handling in the withdraw-all and external-deposits services, updates the MongoDB transaction service, and modifies both the transaction controller and swap controller to support the new "fee" field, ensuring accurate fee processing throughout the entire transaction lifecycle.
- #487
> merge feature/487-transaction-fee into develop

- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/controllers/walletController.ts
- src/controllers/withdrawController.ts
- src/services/swapService.ts
- src/services/transferService.ts
- src/services/web3/userOperationService.ts
Introduced a consistent [op:...] tag format in logs across core operations including transfer, swap, mint NFT, mint NFT copy, create wallet, and withdraw-all. This improves traceability, simplifies debugging, and enables better log-based analytics.
- #508
> merge feature/508-add-tag-logs into develop

- scripts/update_users_name.ts
- [chore] 🔨 add script to update users names
- #502
> merge feature/502-update-user-name into develop

- scripts/update_users_name.ts
- src/controllers/nftController.ts
- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/controllers/walletController.ts
- src/controllers/withdrawController.ts
- src/helpers/formatHelper.ts
- src/models/notificationModel.ts
- src/models/templateModel.ts
- src/services/blockchainService.ts
- src/services/externalDepositsService.ts
- src/services/mongo/mongoNotificationServices.ts
- src/services/mongo/mongoTokenService.ts
- src/services/notificationService.ts
- src/services/swapService.ts
- src/services/transferService.ts
- src/services/web3/userOperationService.ts
- test/models/templateModel.test.ts
- External deposit processing was fixed by removing an incorrect `is_active` token filter that was preventing valid transactions from being accepted. Additionally, it was verified that these deposits are correctly persisted in the database using `mongoTransactionService`, and that the corresponding notification is also stored in the `notifications` collection via `sendReceivedTransferNotification`.
- The backend was updated to persist all user notifications after they are sent. This allows us to optionally display a notification history in the frontend and improve support and debugging for delivery or transaction issues. Each record stores the user ID, message text, timestamp, and delivery channel (bot or push). The message delivery flow itself was not modified.
- Introduced a consistent …
> merge release/20250605 into main

- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/services/blockchainService.ts
- src/services/transferService.ts
- src/services/web3/contractSetupService.ts
- src/services/web3/userOperationService.ts
- Refactored the setupContracts logic to eliminate redundant proxy address computation across services. The update ensures that existing wallet data from the database is reused instead of recalculating the proxy on every operation. As part of this refactor, blockchainService, transactionController, swapService, and transferService were adapted, improving reliability and reducing unnecessary overhead.
- #520
> merge feature/520-avoid-redundant-proxy-computation into develop

- src/services/balanceService.ts
- Included support for WBTC in balance serivce.
- #529
> [feat] :sparkles: add wbtc support in balance service (#529)

- src/controllers/balanceController.ts
- src/services/externalDepositsService.ts
- Added support for toggling user notifications in the external deposits controller and service. Refactored logging, exception handling, and type definitions to improve code clarity and maintainability. Minor naming adjustments for consistency.
- #549
> merge Feature/549-optional-notif-in-external-deposits into develop

- src/controllers/swapController.ts
- src/controllers/transactionController.ts
- src/services/balanceService.ts
- src/services/blockchainService.ts
- src/services/swapService.ts
- src/types/commonType.ts
- Updated token metadata handling by renaming fields in `tokenAddresses` and including `display_symbol` in swap token data responses.
- #558
> merge feature/558-display-symbol-tranfer-and-swap into develop

- src/services/blockchainService.ts
- [fix] :bug: fix token output symbol in swap notification
- ###558
> merge fix/558-swap-output-symbol into develop

- src/services/externalDepositsService.ts
- Fixed an issue where transaction hashes from external deposits were being saved with extra trailing characters, resulting in 74-character strings. The hash is now correctly sliced to 66 characters before being persisted.
- Normalized all wallet addresses stored as `walletFrom` and `walletTo` using EIP-55 checksum casing. This ensures consistent formatting and avoids issues related to lowercase-only addresses.
- #562
- #563
> merge release/20250619-2 into main

- .github/FUNDING.yml
- .vscode/settings.json
> merge feature/funding to develop

- src/services/chatterpointsService.ts
- TheGames logic was updated to normalize both guesses and dictionary answers, ensuring that accented words like “canción” matched user inputs such as “cancion.” The normalizeInput function was applied consistently in comparisons and scoring. Additionally, raw user guesses were stored and displayed instead of their lowercased versions, preserving the original input while maintaining normalized values internally for logic.
- #607
> merge fix/607-games-guesses

- src/controllers/transactionController.ts
- src/services/notificationService.ts
- Enhanced the way transfer errors were surfaced to users. Previously, when a user attempted to transfer to an invalid parameter, such as entering a “name” instead of a wallet address or phone number, or when trying to transfer to themselves, the system caught the error but returned only a generic failure message. With this update, those validation errors were returned with clearer and more contextual details, ensuring the user understood why the transfer failed instead of receiving a vague "there was an error" response. Internal error notifications were also updated to include optional details for better traceability.
- #609
> merge 609-improve-error-handling-transfers into develop

- src/controllers/transactionController.ts
- src/services/chatterpointsService.ts
- src/services/notificationService.ts
- Enhanced the way transfer errors were surfaced to users. Previously, when a user attempted to transfer to an invalid parameter, such as entering a “name” instead of a wallet address or phone number, or when trying to transfer to themselves, the system caught the error but returned only a generic failure message. With this update, those validation errors were returned with clearer and more contextual details, ensuring the user understood why the transfer failed instead of receiving a vague "there was an error" response. Internal error notifications were also updated to include optional details for better traceability.
- #609
> merge release/20251003 into main

- Dockerfile
- cloudbuild.yaml
- example_env
- src/api/routes.ts
- src/api/telegramRoutes.ts
- src/config/constants.ts
- src/config/middlewares/authMiddleware.ts
- src/controllers/balanceController.ts
- src/controllers/chatterpointsController.ts
- src/controllers/telegramController.ts
- src/exxceptions/domain/ChatterpointBusinessError.ts
- src/models/userModel.ts
- src/services/balanceService.ts
- src/services/chatterpointsService.ts
- src/services/mongo/mongoUserService.ts
- src/services/telegram/telegramService.ts
- src/services/userService.ts
- src/types/commonType.ts
- Created the first version of the `ChatterPay Telegram bot` that let users see or `create their wallet`, `check their `balance, and securely `link their Telegram account to an existing WhatsApp-based account` using a simple 6-digit code. The goal was to validate the end-to-end experience with clear, friendly copy and lightweight flows so product and stakeholders could quickly review how the core actions felt in chat.
- #613
> merge release/20251005 into main

- src/controllers/telegramController.ts
- Fixed an issue where Telegram sometimes ignored phone numbers shared through **“Share my phone”** due to lost session flags after a restart, ensuring numbers are now always detected and linked correctly to user accounts.
- #616
> merge fix/share-my-phone into develop
